"use strict";
const assert = require("node:assert/strict");
const fs = require("node:fs");
const path = require("node:path");
const migration = fs.readFileSync(path.join(__dirname, "..", "db", "migrations", "012_affiliate_creator_authorization_function_column_qualification.sql"), "utf8");
const compact = migration.replace(/\s+/g, " ").toLowerCase();
assert.match(migration, /^BEGIN;[\s\S]*COMMIT;\s*$/);
assert.equal((migration.match(/CREATE OR REPLACE FUNCTION public\.(?:begin_affiliate_creator_authorization|accept_affiliate_creator_authorization_callback)\(/g) || []).length, 2);
assert.equal((migration.match(/SESSION_USER::pg_catalog\.regrole::pg_catalog\.oid/g) || []).length, 2);
assert.equal((migration.match(/SECURITY DEFINER SET search_path = pg_catalog, public, pg_temp/g) || []).length, 2);
assert.match(compact, /connection_row\.authorization_state, connection_row\.authorization_revision, connection_row\.credential_revision/);
assert.doesNotMatch(compact, /select authorization_state, authorization_revision, credential_revision/);
assert.match(compact, /credential_row\.connection_id = p_connection_id/);
assert.match(compact, /state_row\.connection_id = p_connection_id/);
assert.match(compact, /state_row\.authorization_revision = p_authorization_revision/);
assert.equal((migration.match(/REVOKE ALL ON FUNCTION public\./g) || []).length, 2);
assert.equal((migration.match(/GRANT EXECUTE ON FUNCTION public\./g) || []).length, 2);
assert.doesNotMatch(compact, /create role|alter role|grant .* to public|default privileges|process\.env|require\(|fetch\s*\(|https?:\/\/|redis|upstash|token-store|route|logger|cache|retry/);
console.log("Affiliate Creator authorization function column-qualification schema tests passed.");
