"use strict";
const assert=require("node:assert/strict");
const {normalizeCreatorTokenResponse}=require("../lib/tiktok-shop-affiliate-creator-authorization-contract");
const {create,AffiliateCreatorRuntimeServiceError}=require("../lib/tiktok-shop-affiliate-creator-runtime-service");
const startHandler=require("../api/auth/tiktok-shop/affiliate-creator/start").createHandler;
const callbackHandler=require("../api/auth/tiktok-shop/affiliate-creator/callback").createHandler;
const STATE="A".repeat(43),CONNECTION="b2222222-2222-4222-8222-222222222222",ACCOUNT="a1111111-1111-4111-8111-111111111111",KEY=Buffer.alloc(32,1).toString("base64url"),NOW=1700000000000;
function cfg(enabled=true){return{read(){if(!enabled)throw Error();return{environment:"sandbox",databaseUrl:"postgresql://northstar_affiliate_creator_runtime@x.neon.tech/neondb?sslmode=verify-full",appKey:"app",appSecret:"secret",keyring:KEY};}};}
function token(){return normalizeCreatorTokenResponse({code:0,message:"",request_id:"discarded",data:{access_token:"private-access",refresh_token:"private-refresh",open_id:"private-open-id",user_type:1,access_token_expire_in:1700003600,refresh_token_expire_in:1700086400,granted_scopes:["creator.affiliate.info"]}},{now:NOW});}
function build({enabled=true,profile={creatorUserId:"creator",selectionRegion:null,registerRegion:null,sellerType:null,permissions:[],userType:null},tokenResult=token()}={}){const calls=[],state={create:()=>STATE,digest:v=>{if(v!==STATE)throw Error();return"d".repeat(64);},connectionId:v=>{if(v!==STATE)throw Error();return CONNECTION;}},db={async begin(v){calls.push(["begin",v]);return{connection_id:CONNECTION,authorization_revision:1};},async accept(v){calls.push(["accept",v]);return{connection_id:CONNECTION,authorization_revision:2,credential_revision:0};},async account(){calls.push(["account"]);return{account_id:ACCOUNT};},async complete(v){calls.push(["complete",v]);}},client={authorizationUrl:v=>{calls.push(["url",v]);return`https://shop.tiktok.com/alliance/creator/auth?state=${v}&scope=creator.affiliate.info`;},async exchange(v){calls.push(["exchange",v]);return tokenResult;},async profile(v){calls.push(["profile",v]);return profile;}},persistence={prepare:v=>{calls.push(["prepare",v]);return Object.freeze(Object.create(null));}};return{calls,service:create({config:cfg(enabled),state,createDatabase:()=>db,createTikTokClient:()=>client,createPersistence:()=>persistence,createCryptographer:()=>Object.freeze({encrypt(){}}),clock:()=>NOW})};}
function response(){const headers={};return{headers,setHeader(k,v){headers[k]=v;},end(v=""){this.body=v;}};}
async function serviceTests(){const {service,calls}=build(),start=await service.start();assert.match(start.redirect,/^https:\/\/shop\.tiktok\.com\/alliance\/creator\/auth/);assert.equal(calls[0][1].stateDigest,"d".repeat(64));assert.equal(JSON.stringify(calls[0][1]).includes(STATE),false);assert.equal(calls[1][1],STATE);const disabled=build({enabled:false});await assert.rejects(()=>disabled.service.start(),AffiliateCreatorRuntimeServiceError);assert.deepEqual(disabled.calls,[]);const flow=build(),profile=await flow.service.callback({state:STATE,code:"code"});assert.deepEqual(Object.keys(profile),["creatorUserId","selectionRegion","registerRegion","sellerType","permissions","userType"]);assert.deepEqual(flow.calls.map(x=>x[0]),["accept","exchange","account","profile","prepare","complete"]);assert.equal(JSON.stringify(flow.calls[4][1]).includes("private-access"),true);assert.equal(JSON.stringify(flow.calls[5][1]).includes("private-access"),false);const failed=build({profile:null});await assert.rejects(()=>failed.service.callback({state:STATE,code:"code"}),AffiliateCreatorRuntimeServiceError);assert.equal(failed.calls.some(x=>x[0]==="complete"),false);const denied=build();await assert.rejects(()=>denied.service.callback({state:STATE,error:"access_denied"}),AffiliateCreatorRuntimeServiceError);assert.deepEqual(denied.calls.map(x=>x[0]),["accept"]);}
async function routeTests(){let begins=0;const start=startHandler({createService:()=>({async start(){begins++;return{redirect:"https://shop.tiktok.com/alliance/creator/auth?state=x"};}}),diagnosticStage:()=>null}),sr=response();await start({method:"GET"},sr);assert.equal(begins,1);assert.equal(sr.statusCode,302);assert.equal(sr.headers["Cache-Control"],"private, no-store, max-age=0");const diagnostic=startHandler({diagnosticStage:()=>"enable_flag",createService:()=>({async start(){throw Error("must not start");}})}),dr=response();await diagnostic({method:"GET"},dr);assert.equal(dr.statusCode,404);assert.equal(dr.body,'{"error":"affiliate_creator_runtime_unavailable"}');const databaseFailure=startHandler({diagnosticStage:()=>null,previewDiagnostic:()=>true,createService:()=>{const error=Error();error.stage="database_initialization";throw error;}}),br=response();await databaseFailure({method:"GET"},br);assert.equal(br.statusCode,404);let values;const callback=callbackHandler({createService:()=>({async callback(v){values=v;return{creatorUserId:"creator",selectionRegion:null,registerRegion:null,sellerType:null,permissions:[],userType:null};}})}),cr=response();await callback({method:"GET",url:`/?state=${STATE}&code=code`},cr);assert.equal(cr.statusCode,200);assert.equal(values.state,STATE);const invalid=response();await callback({method:"GET",url:`/?state=${STATE}&code=a&code=b`},invalid);assert.equal(invalid.statusCode,400);assert.equal(invalid.body.includes(STATE),false);}
(async()=>{await serviceTests();await routeTests();console.log("Affiliate Creator runtime service and route tests passed.");})().catch(e=>{process.stderr.write(`${e.stack}\n`);process.exitCode=1;});
