"use strict";
const runtimeConfig = require("../../../../lib/tiktok-shop-affiliate-creator-runtime-config");
const state = require("../../../../lib/tiktok-shop-affiliate-creator-runtime-state");
const database = require("../../../../lib/tiktok-shop-affiliate-creator-runtime-db");
const client = require("../../../../lib/tiktok-shop-affiliate-creator-runtime-tiktok-client");
const persistence = require("../../../../lib/tiktok-shop-affiliate-creator-runtime-persistence");
const service = require("../../../../lib/tiktok-shop-affiliate-creator-runtime-service");
const MAX_CODE = 2048, MAX_ERROR = 128;
const PREVIEW_DIAGNOSTIC_BRANCH = "sandbox/tiktok-sandbox-integration";
function send(res, status, value) { res.statusCode = status; res.setHeader("Cache-Control", "private, no-store, max-age=0"); res.setHeader("Content-Type", "application/json; charset=utf-8"); res.end(JSON.stringify(value)); }
function parameters(url) { const allowed = new Set(["code", "state", "error"]); for (const [key] of url.searchParams) if (!allowed.has(key)) throw new Error("invalid"); const read = (key, max) => { const values = url.searchParams.getAll(key); if (values.length > 1 || (values.length === 1 && (!values[0] || values[0].length > max))) throw new Error("invalid"); return values[0]; }; const code = read("code", MAX_CODE), rawState = read("state", 128), error = read("error", MAX_ERROR); if (!rawState || (code && error) || (!code && !error)) throw new Error("invalid"); return error ? { state: rawState, error } : { state: rawState, code }; }
function isPreviewDiagnostic(env = process.env) { return env.VERCEL_ENV === "preview" && env.VERCEL_GIT_COMMIT_REF === PREVIEW_DIAGNOSTIC_BRANCH; }
function logStage(stage) { console.info(`affiliate_creator_preview_stage=${stage}`); }
function createHandler(dependencies = {}) { const createService = dependencies.createService || (onStage => { const values = runtimeConfig.read(); return service.create({ config: { read: () => values }, state, createDatabase: database.create, createTikTokClient: client.create, createPersistence: persistence.create, onStage }); }); const previewDiagnostic = dependencies.previewDiagnostic || isPreviewDiagnostic; return async function handler(req, res) { if (req.method !== "GET") { res.setHeader("Allow", "GET"); return send(res, 405, { error: "affiliate_creator_runtime_unavailable" }); } let values; try { values = parameters(new URL(req.url, "https://sandbox-api.northstar-creator.com")); } catch { return send(res, 400, { error: "affiliate_creator_runtime_unavailable" }); } let stage = "database_initialization"; let runtime; try { runtime = createService(value => { stage = value; }); } catch { if (previewDiagnostic()) logStage(stage); return send(res, 404, { error: "affiliate_creator_runtime_unavailable" }); } try { const profile = await runtime.callback(values); return send(res, 200, { profile }); } catch { if (previewDiagnostic()) logStage(stage); return send(res, 400, { error: "affiliate_creator_runtime_unavailable" }); } }; }
module.exports = createHandler(); module.exports.createHandler = createHandler; module.exports.config = { runtime: "nodejs" };
