window.NORTHSTAR_SANDBOX_DATA = {
  accounts: [
    {
      id: "raised-right",
      name: "Raised Right",
      focus: "Product-led commerce",
      followers: 84200,
      followerChange: 318
    },
    {
      id: "truth-tuned-tribe",
      name: "Truth Tuned Tribe",
      focus: "Education and curiosity",
      followers: 61450,
      followerChange: 486
    }
  ],
  revenueSources: [
    { id: "shop", name: "TikTok Shop", color: "gold" },
    { id: "rewards", name: "Creator Rewards", color: "teal" },
    { id: "go", name: "TikTok GO", color: "blue" }
  ],
  products: [
    {
      id: "garden-hoe",
      accountId: "raised-right",
      name: "2-in-1 Garden Hoe and Weed Puller",
      image: "GH",
      workflowStep: 4,
      sampleStep: "Earnings",
      earnings: 1178,
      gmv: 8940,
      sales: 86,
      views: 276000,
      updatedAt: "2026-07-15",
      insight: "Evening videos are still converting after the first spike."
    },
    {
      id: "tds-meter",
      accountId: "raised-right",
      name: "Digital Water Quality Tester",
      image: "WT",
      workflowStep: 4,
      sampleStep: "Earnings",
      earnings: 426,
      gmv: 3180,
      sales: 37,
      views: 84300,
      updatedAt: "2026-07-14",
      insight: "Curiosity hooks create stronger saves than pure demos."
    },
    {
      id: "ai-glasses",
      accountId: "truth-tuned-tribe",
      name: "Smart AI Camera Glasses",
      image: "AI",
      workflowStep: 2,
      sampleStep: "Content",
      earnings: 74,
      gmv: 640,
      sales: 6,
      views: 41200,
      updatedAt: "2026-07-16",
      insight: "The product needs a creator-led demonstration angle."
    },
    {
      id: "peptide-playbook",
      accountId: "truth-tuned-tribe",
      name: "Complete Peptide Protocols Playbook",
      image: "PP",
      workflowStep: 4,
      sampleStep: "Earnings",
      earnings: 392,
      gmv: 3290,
      sales: 42,
      views: 143900,
      updatedAt: "2026-07-13",
      insight: "Authority positioning is producing both earnings and audience growth."
    },
    {
      id: "solar-lantern",
      accountId: "raised-right",
      name: "Hanging Solar Lantern",
      image: "SL",
      workflowStep: 3,
      sampleStep: "Videos",
      earnings: 124,
      gmv: 940,
      sales: 11,
      views: 37600,
      updatedAt: "2026-07-11",
      insight: "Lifestyle visuals are outperforming product-only shots."
    },
    {
      id: "hotel-cafe",
      accountId: "truth-tuned-tribe",
      name: "Historic Hotel Cafe Feature",
      image: "GO",
      workflowStep: 3,
      sampleStep: "Videos",
      earnings: 188,
      gmv: 0,
      sales: 18,
      views: 93500,
      updatedAt: "2026-07-12",
      insight: "Local curiosity videos are creating strong TikTok GO intent."
    }
  ],
  videos: [
    {
      id: "v1",
      accountId: "raised-right",
      productId: "garden-hoe",
      title: "If you hate pulling weeds, try this first",
      thumbnail: "GH",
      date: "2026-07-16",
      time: "7:42 PM",
      views: 88200,
      likes: 2600,
      comments: 118,
      shares: 410,
      earnings: 328,
      gmv: 2460,
      units: 24,
      sourceIds: ["shop"]
    },
    {
      id: "v2",
      accountId: "raised-right",
      productId: "garden-hoe",
      title: "Stop bending over to pull weeds",
      thumbnail: "GH",
      date: "2026-07-12",
      time: "8:13 PM",
      views: 126000,
      likes: 4100,
      comments: 174,
      shares: 690,
      earnings: 512,
      gmv: 3940,
      units: 41,
      sourceIds: ["shop"]
    },
    {
      id: "v3",
      accountId: "raised-right",
      productId: "tds-meter",
      title: "I tested my tap water and did not expect this",
      thumbnail: "WT",
      date: "2026-07-15",
      time: "7:04 PM",
      views: 64300,
      likes: 1900,
      comments: 81,
      shares: 310,
      earnings: 214,
      gmv: 1640,
      units: 20,
      sourceIds: ["shop"]
    },
    {
      id: "v4",
      accountId: "raised-right",
      productId: "solar-lantern",
      title: "The porch light that made my yard feel finished",
      thumbnail: "SL",
      date: "2026-07-11",
      time: "6:38 PM",
      views: 37600,
      likes: 850,
      comments: 22,
      shares: 74,
      earnings: 124,
      gmv: 940,
      units: 11,
      sourceIds: ["shop"]
    },
    {
      id: "v5",
      accountId: "truth-tuned-tribe",
      productId: "peptide-playbook",
      title: "I researched peptide protocols so you do not have to",
      thumbnail: "PP",
      date: "2026-07-13",
      time: "2:09 PM",
      views: 143900,
      likes: 5200,
      comments: 211,
      shares: 1280,
      earnings: 235,
      gmv: 1840,
      units: 23,
      sourceIds: ["shop", "rewards"]
    },
    {
      id: "v6",
      accountId: "truth-tuned-tribe",
      productId: "ai-glasses",
      title: "These glasses record what your hands are doing",
      thumbnail: "AI",
      date: "2026-07-16",
      time: "9:18 AM",
      views: 19200,
      likes: 460,
      comments: 39,
      shares: 94,
      earnings: 42,
      gmv: 320,
      units: 3,
      sourceIds: ["shop", "rewards"]
    },
    {
      id: "v7",
      accountId: "truth-tuned-tribe",
      productId: "hotel-cafe",
      title: "This hidden cafe is inside an old hotel",
      thumbnail: "GO",
      date: "2026-07-12",
      time: "4:45 PM",
      views: 93500,
      likes: 7100,
      comments: 344,
      shares: 1260,
      earnings: 188,
      gmv: 0,
      units: 18,
      sourceIds: ["go", "rewards"]
    },
    {
      id: "v8",
      accountId: "truth-tuned-tribe",
      productId: "peptide-playbook",
      title: "The mistake people make when learning about peptides",
      thumbnail: "PP",
      date: "2026-07-09",
      time: "8:28 PM",
      views: 88200,
      likes: 3400,
      comments: 176,
      shares: 840,
      earnings: 157,
      gmv: 1450,
      units: 19,
      sourceIds: ["shop", "rewards"]
    },
    {
      id: "v9",
      accountId: "raised-right",
      productId: "tds-meter",
      title: "Before you buy bottled water, test this",
      thumbnail: "WT",
      date: "2026-07-07",
      time: "7:56 PM",
      views: 20100,
      likes: 510,
      comments: 18,
      shares: 58,
      earnings: 68,
      gmv: 520,
      units: 7,
      sourceIds: ["shop"]
    },
    {
      id: "v10",
      accountId: "raised-right",
      productId: "garden-hoe",
      title: "Garden cleanup in under ten minutes",
      thumbnail: "GH",
      date: "2026-07-03",
      time: "11:12 AM",
      views: 61700,
      likes: 1220,
      comments: 42,
      shares: 140,
      earnings: 206,
      gmv: 1570,
      units: 21,
      sourceIds: ["shop"]
    },
    {
      id: "v11",
      accountId: "truth-tuned-tribe",
      productId: "ai-glasses",
      title: "A hands-free camera angle creators will understand",
      thumbnail: "AI",
      date: "2026-07-05",
      time: "1:24 PM",
      views: 22000,
      likes: 590,
      comments: 64,
      shares: 116,
      earnings: 32,
      gmv: 320,
      units: 3,
      sourceIds: ["shop", "rewards"]
    },
    {
      id: "v12",
      accountId: "truth-tuned-tribe",
      productId: "hotel-cafe",
      title: "Where locals go when tourists miss the turn",
      thumbnail: "GO",
      date: "2026-07-01",
      time: "5:10 PM",
      views: 39200,
      likes: 2100,
      comments: 102,
      shares: 380,
      earnings: 74,
      gmv: 0,
      units: 8,
      sourceIds: ["go", "rewards"]
    }
  ],
  opportunities: [
    {
      id: "opp-garden-repeat",
      accountId: "raised-right",
      type: "Product opportunity",
      title: "Garden Hoe is still converting",
      body: "It has earnings this week but no new video since the strongest evening post.",
      targetType: "product",
      targetId: "garden-hoe"
    },
    {
      id: "opp-evening",
      accountId: "raised-right",
      type: "Posting-time signal",
      title: "Evening posts are producing stronger shop sales",
      body: "Raised Right product videos posted after 7:00 PM are leading the mock period.",
      targetType: "video",
      targetId: "v1"
    },
    {
      id: "opp-education",
      accountId: "truth-tuned-tribe",
      type: "Creator Rewards signal",
      title: "Education videos are compounding",
      body: "Truth Tuned Tribe rewards are strongest when the hook promises researched clarity.",
      targetType: "video",
      targetId: "v5"
    },
    {
      id: "opp-ai-content",
      accountId: "truth-tuned-tribe",
      type: "Content step",
      title: "AI Glasses needs a clearer demo",
      body: "The product has interest signals but needs a sharper hands-free use case.",
      targetType: "product",
      targetId: "ai-glasses"
    }
  ],
  dailyEarnings: [
    { date: "2026-07-01", raisedRight: 86, truthTunedTribe: 112 },
    { date: "2026-07-03", raisedRight: 206, truthTunedTribe: 96 },
    { date: "2026-07-05", raisedRight: 74, truthTunedTribe: 132 },
    { date: "2026-07-07", raisedRight: 148, truthTunedTribe: 121 },
    { date: "2026-07-09", raisedRight: 184, truthTunedTribe: 157 },
    { date: "2026-07-11", raisedRight: 124, truthTunedTribe: 86 },
    { date: "2026-07-13", raisedRight: 232, truthTunedTribe: 235 },
    { date: "2026-07-15", raisedRight: 214, truthTunedTribe: 102 },
    { date: "2026-07-16", raisedRight: 328, truthTunedTribe: 42 }
  ]
};
